#!/usr/bin/env python3
"""
Figure S2D – Scan candidate 7-mer space

Description
-----------
Generate all possible 7-mers from selected candidate miRNA sequences and
compare them against a dictionary of known canonical miRNA seeds.

Inputs
------
--input_tsv
    Candidate TSV. Expected columns or tab-separated fields:
    - candidate/name
    - mature sequence
    - canonical seed

--seed_db
    Known seed dictionary TSV generated by FigureS2D_build_known_seed_dictionary.py.
    Expected columns:
    - miRNA_id
    - family
    - mature_seq
    - canonical_seed

Outputs
-------
--out_long
    Long-format TSV with one row per candidate 7-mer.

--out_summary
    Summary TSV with one row per candidate.

Usage
-----
python FigureS2D_scan_candidate_7mer_space.py \\
  --input_tsv path/to/brumir_DE_seeds_para_analisis_kmers.tsv \\
  --seed_db path/to/known_seed_dictionary.tsv \\
  --out_long path/to/candidate_7mer_long.tsv \\
  --out_summary path/to/candidate_7mer_summary.tsv
"""

import argparse
import csv
import sys
from collections import defaultdict
from pathlib import Path


CONTROL_MAP = {
    "hsa_miR-660-5p": "known_miRNA_control",
    "known_seed_A": "known_seed_control",
    "hsa-miR-novel_A": "novel_candidate",
    "hsa-miR-novel_B": "novel_candidate",
    "hsa-miR-novel_C": "novel_candidate",
    "hsa-miR-novel_D": "novel_candidate",
}


LONG_FIELDS = [
    "candidate",
    "control_type",
    "mature_seq",
    "kmer_start_pos_1based",
    "kmer_7mer",
    "is_canonical_seed_2_8",
    "kmer_status",
    "matched_known_miRNAs",
    "matched_families",
]


SUMMARY_FIELDS = [
    "candidate",
    "control_type",
    "mature_seq",
    "canonical_seed_2_8",
    "canonical_seed_status",
    "canonical_seed_matched_families",
    "n_total_7mers",
    "n_matching_known_7mers",
    "matching_positions",
    "matched_known_7mers",
    "matched_families_all_positions",
]


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Generate all possible 7-mers from candidate miRNAs and compare "
            "them against known canonical miRNA seeds."
        )
    )
    parser.add_argument(
        "--input_tsv",
        required=True,
        help="Input TSV with candidate, mature sequence, and canonical seed.",
    )
    parser.add_argument(
        "--seed_db",
        required=True,
        help="Known seed dictionary TSV.",
    )
    parser.add_argument(
        "--out_long",
        required=True,
        help="Output long-format TSV.",
    )
    parser.add_argument(
        "--out_summary",
        required=True,
        help="Output summary TSV.",
    )

    return parser.parse_args()


def validate_input_file(path: Path, label: str) -> None:
    """Validate that an input file exists."""
    if not path.exists():
        sys.exit(f"ERROR: {label} not found: {path}")
    if not path.is_file():
        sys.exit(f"ERROR: {label} is not a file: {path}")


def load_known_seed_dictionary(seed_db: Path):
    """Load known canonical seeds and associated miRNA IDs/families."""
    seed_to_ids = defaultdict(list)
    seed_to_families = defaultdict(set)

    with seed_db.open("r", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")

        required_columns = {"canonical_seed", "miRNA_id", "family"}
        missing_columns = required_columns - set(reader.fieldnames or [])

        if missing_columns:
            sys.exit(
                "ERROR: Missing required columns in seed dictionary "
                f"{seed_db}: {', '.join(sorted(missing_columns))}"
            )

        for row in reader:
            seed = row["canonical_seed"].strip().upper().replace("T", "U")
            seed_to_ids[seed].append(row["miRNA_id"])
            seed_to_families[seed].add(row["family"])

    return seed_to_ids, seed_to_families


def parse_candidate_line(line: str, input_path: Path, line_number: int):
    """
    Parse one candidate input line.

    Original input format is preserved:
    name<TAB>mature_seq<TAB>canonical_seed
    """
    fields = line.split("\t")

    if len(fields) != 3:
        sys.exit(
            "ERROR: Expected exactly 3 tab-separated fields in "
            f"{input_path} at line {line_number}: candidate, mature_seq, canonical_seed"
        )

    name, mature_seq, canonical_seed = fields
    mature_seq = mature_seq.upper().replace("T", "U")
    canonical_seed = canonical_seed.upper().replace("T", "U")

    return name, mature_seq, canonical_seed


def scan_candidate(name, mature_seq, canonical_seed, seed_to_ids, seed_to_families):
    """Generate long and summary rows for one candidate sequence."""
    long_rows = []

    total_7mers = 0
    matched_positions = []
    matched_seeds = set()
    matched_families = set()

    for index in range(len(mature_seq) - 6):
        kmer = mature_seq[index:index + 7]
        pos1 = index + 1  # 1-based position
        is_canonical = pos1 == 2
        match_status = "known_seed_match" if kmer in seed_to_ids else "novel_seed"
        matched_ids = ",".join(sorted(seed_to_ids.get(kmer, [])))
        families = ",".join(sorted(seed_to_families.get(kmer, [])))

        if kmer in seed_to_ids:
            matched_positions.append(str(pos1))
            matched_seeds.add(kmer)
            matched_families.update(seed_to_families[kmer])

        long_rows.append(
            {
                "candidate": name,
                "control_type": CONTROL_MAP.get(name, "candidate"),
                "mature_seq": mature_seq,
                "kmer_start_pos_1based": pos1,
                "kmer_7mer": kmer,
                "is_canonical_seed_2_8": "yes" if is_canonical else "no",
                "kmer_status": match_status,
                "matched_known_miRNAs": matched_ids if matched_ids else "-",
                "matched_families": families if families else "-",
            }
        )

        total_7mers += 1

    canonical_status = (
        "known_seed" if canonical_seed in seed_to_ids else "novel_seed"
    )

    canonical_families = (
        ",".join(sorted(seed_to_families.get(canonical_seed, [])))
        if canonical_seed in seed_to_ids
        else "-"
    )

    summary_row = {
        "candidate": name,
        "control_type": CONTROL_MAP.get(name, "candidate"),
        "mature_seq": mature_seq,
        "canonical_seed_2_8": canonical_seed,
        "canonical_seed_status": canonical_status,
        "canonical_seed_matched_families": canonical_families,
        "n_total_7mers": total_7mers,
        "n_matching_known_7mers": len(matched_seeds),
        "matching_positions": ",".join(matched_positions) if matched_positions else "-",
        "matched_known_7mers": ",".join(sorted(matched_seeds)) if matched_seeds else "-",
        "matched_families_all_positions": (
            ",".join(sorted(matched_families)) if matched_families else "-"
        ),
    }

    return long_rows, summary_row


def write_tsv(path: Path, rows, fieldnames) -> None:
    """Write rows to a TSV file."""
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)


def main():
    args = parse_args()

    input_path = Path(args.input_tsv)
    seed_db_path = Path(args.seed_db)
    out_long_path = Path(args.out_long)
    out_summary_path = Path(args.out_summary)

    validate_input_file(input_path, "Input candidate TSV")
    validate_input_file(seed_db_path, "Known seed dictionary TSV")

    seed_to_ids, seed_to_families = load_known_seed_dictionary(seed_db_path)

    long_rows = []
    summary_rows = []

    with input_path.open("r") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()

            if not line:
                continue

            name, mature_seq, canonical_seed = parse_candidate_line(
                line,
                input_path,
                line_number,
            )

            candidate_long_rows, candidate_summary_row = scan_candidate(
                name,
                mature_seq,
                canonical_seed,
                seed_to_ids,
                seed_to_families,
            )

            long_rows.extend(candidate_long_rows)
            summary_rows.append(candidate_summary_row)

    if not long_rows:
        sys.exit("ERROR: No candidate 7-mers were generated.")

    if not summary_rows:
        sys.exit("ERROR: No candidate summary rows were generated.")

    write_tsv(out_long_path, long_rows, LONG_FIELDS)
    write_tsv(out_summary_path, summary_rows, SUMMARY_FIELDS)

    print("Written:", out_long_path)
    print("Written:", out_summary_path)


if __name__ == "__main__":
    main()
