#!/usr/bin/env python3
"""
Figure2B_prepare_venn_counts.py

Prepare the two-set Venn counts used in Figure 2b from the
core-set tables generated by nf-Sarcopipe.

For each method, reports:
- Active-only
- Shared
- Sedentary-only
- Active core total
- Sedentary core total
- Core union

The presence thresholds are not recalculated or hard-coded here.
The input core-set tables already contain the candidates selected
by the corresponding nf-Sarcopipe configuration.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, Set


def read_core_sets(path: Path) -> tuple[Set[str], Set[str]]:
    active: Set[str] = set()
    sedentary: Set[str] = set()

    if not path.is_file():
        raise SystemExit(f"[ERROR] File not found: {path}")

    with path.open(encoding="utf-8", errors="replace") as handle:
        reader = csv.DictReader(handle, delimiter="\t")

        if reader.fieldnames is None:
            raise SystemExit(f"[ERROR] Empty table: {path}")

        required = {"set", "miRNA"}
        if not required.issubset(reader.fieldnames):
            raise SystemExit(
                f"[ERROR] Expected columns {sorted(required)} in {path}. "
                f"Found: {reader.fieldnames}"
            )

        for row in reader:
            set_name = row["set"].strip()
            candidate = row["miRNA"].strip()

            if not candidate:
                continue

            if set_name == "athlete_core":
                active.add(candidate)
            elif set_name == "sedentary_core":
                sedentary.add(candidate)

    return active, sedentary


def summarize(path: Path) -> Dict[str, int]:
    active, sedentary = read_core_sets(path)

    shared = active & sedentary
    active_only = active - sedentary
    sedentary_only = sedentary - active
    union = active | sedentary

    return {
        "active_only": len(active_only),
        "shared": len(shared),
        "sedentary_only": len(sedentary_only),
        "active_core_total": len(active),
        "sedentary_core_total": len(sedentary),
        "core_union": len(union),
    }


def main() -> None:
    parser = argparse.ArgumentParser()

    parser.add_argument("--brumir", required=True)
    parser.add_argument("--mirdeep2_known", required=True)
    parser.add_argument("--mirdeep2_novel", required=True)
    parser.add_argument("--out", required=True)

    args = parser.parse_args()

    inputs = [
        ("BrumiR-RF", Path(args.brumir)),
        ("miRDeep2 known", Path(args.mirdeep2_known)),
        ("miRDeep2 novel", Path(args.mirdeep2_novel)),
    ]

    output_path = Path(args.out)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    columns = [
        "method",
        "active_only",
        "shared",
        "sedentary_only",
        "active_core_total",
        "sedentary_core_total",
        "core_union",
    ]

    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=columns,
            delimiter="\t",
        )
        writer.writeheader()

        for method, path in inputs:
            writer.writerow({
                "method": method,
                **summarize(path),
            })

    print(f"[OK] Wrote: {output_path}")


if __name__ == "__main__":
    main()
PY
